### ISSUE TITLE
Update obfuscator to 0.14.3 version

### ISSUE THREAD

**Issue by sanex3339** [javascript-obfuscator/rollup-plugin-javascript-obfuscator#1]
Please, update obfuscator to 0.14.3 version.

For each obfuscated file you should change `identifiersPrefix` option value on unique one to avoid conflicts between generated identifiers from different files.

**Comment by getkey** [comment]
Relevant PR #3.

**Comment by Wain-PC** [comment]
Obfuscator version has been updated through the PR, thank you!
